trigger:
  - '*'

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build and publish
  jobs: 
  - job: Build
    displayName: Build and publish Docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: Docker@2
      displayName: Tag master image
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'push'
        tags: 'master'
