trigger:
  - '*'

resources:
- repo: self

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    tags: |
      master
      $(Build.SourceVersion)
  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    tags: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build and publish
  jobs: 
  - job: Build
    displayName: Build and publish Docker image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tags)'