trigger:
  - '*'

resources:
- repo: self

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/head/master') }}:
    tag: 'master'
  ${{ if ne(variables['Build.SourceBranch'], 'refs/head/master') }}:
    tag: '$(Build.SourceVersion)'

stages:
- stage: BuildAndDeploy
  displayName: Build and deploy image
  jobs: 
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

  - job: Deploy
    displayName: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '$(knownHostsEntry)'
        sshPublicKey: '$(sshPublicKey)'
        sshKeySecureFile: '$(sshKeySecureFile)'