trigger:
  - '*'

resources:
- repo: self

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/head/master') }}:
    tag: 'master'
  ${{ if ne(variables['Build.SourceBranch'], 'refs/head/master') }}:
    tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build
  jobs: 
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'