trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push Docker image
      inputs:
        containerRegistry: 'Docker Hub - michaelsmithxyz'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: '$(knownHostsEntry)'
        sshPublicKey: '$(sshPublicKey)'
        sshKeySecureFile: '$(sshKeySecureFile)'