version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/michaelsmith.xyz
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - ./*.html
            - files/
            - ./*.css
            - ./*.js

  test:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/michaelsmith.xyz
    steps:
      - attach_workspace:
          at: ~/michaelsmith.xyz
      - run:
          name: Test html
          command: htmlproofer --disable-external --check-html .

  deploy:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/michaelsmith.xyz
    steps:
      - attach_workspace:
          at: ~/michaelsmith.xyz
      - add_ssh_keys:
          fingerprints:
            - "ce:33:23:22:42:a5:9c:8a:79:31:57:12:30:5a:ca:15"
      - run:
          name: Keyscan target server
          command: ssh-keyscan -H -p $SSH_PORT $DEPLOY_HOST >> ~/.ssh/known_hosts
      - deploy:
          name: deploy
          command: |
              if [ "${CIRCLE_BRANCH}" = "master" ]; then
                rsync -Oavce "ssh -p ${SSH_PORT}" ./* $DEPLOY_USER@$DEPLOY_HOST:$SITE_PATH
              else
                echo "Not master branch, dry run only"
              fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          context: Web Server Prod
          filters:
            branches:
              only: master
          requires:
            - build
            - test
