apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: michaelsmithxyz-issuer
spec:
  acme:
    email: smithr.michael1997@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: michaelsmithxyz-private-key
    solvers:
      - http01:
          ingress:
            class: nginx
