apiVersion: apps/v1
kind: Deployment
metadata:
  name: smithdotpizza
  labels:
    app: smithdotpizza
spec:
  selector:
    matchLabels:
      app: smithdotpizza
  replicas: 1
  template:
    metadata:
      labels:
        app: smithdotpizza
    spec:
      containers:
        - name: smithdotpizza
          image: michaelsmithxyz/smith.pizza:latest
          env:
            - name: Cache__Connection
              value: "smithpizza-redis"
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 80
