apiVersion: v1
kind: Service
metadata:
  name: smithdotpizza
  labels:
    app: smithdotpizza
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: smithdotpizza
