name: 'Setup pnpm'
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
      with:
        version: 10.33.0
    - uses: actions/setup-node@v6
      with:
        node-version: 24.14.0

