apiVersion: v1
kind: Service
metadata:
  name: michaelsmithxyz
  labels:
    app: michaelsmith.xyz
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: michaelsmith.xyz
