apiVersion: apps/v1
kind: Deployment
metadata:
  name: michaelsmithxyz
  labels:
    app: michaelsmith.xyz
spec:
  selector:
    matchLabels:
      app: michaelsmith.xyz
  replicas: 1
  template:
    metadata:
      labels:
        app: michaelsmith.xyz
    spec:
      containers:
        - name: michaelsmithxyz
          image: michaelsmithxyz/michaelsmith.xyz:master
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 80
