name: Check smith.pizza
on:
  push:
    paths:
      - smith.pizza/**
jobs:
  typecheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: make smith.pizza/check