name: Check
on: [push]
jobs:
  typecheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - run: make check
