name: Deploy michaelsmith.xyz
on:
  push:
    branches:
      - master
    paths:
      - michaelsmith.xyz/**
      - deno.json
      - .github/workflows/deploy-michaelsmith-xyz.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - run: make michaelsmith.xyz/build

      - uses: denoland/deployctl@v1
        with:
          project: msmithxyz-homepage
          entrypoint: michaelsmith.xyz/src/main.tsx
          root: .
          include: |
            deno.json
            michaelsmith.xyz/deno.json
            michaelsmith.xyz/src
            michaelsmith.xyz/static
            smith.pizza/deno.json
          exclude: |
            **/*.test.ts
