name: Deploy smith.pizza
on:
  push:
    branches:
      - master
    paths:
      - smith.pizza/**
      - deno.json
      - .github/workflows/deploy-smith-pizza.yml

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.3
      - uses: denoland/deployctl@v1
        with:
          project: smith-pizza
          entrypoint: smith.pizza/src/main.ts
          include: |
            deno.json
            smith.pizza/deno.json
            smith.pizza/src