name: Workflow
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - run: |
          pnpm i --frozen-lockfile
          make check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - run: make test

  deploy-dev:
    name: Deploy michaelsmith.xyz dev
    if: github.event_name == 'workflow_dispatch'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          make michaelsmith.xyz/deploy

  deploy-prod:
    name: Deploy michaelsmith.xyz prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          export DEPLOY_ENV="prod"
          make michaelsmith.xyz/deploy

  deploy-smith-pizza:
    name: Deploy smith.pizza
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.3
      - uses: denoland/deployctl@v1
        with:
          project: smith-pizza
          entrypoint: smith.pizza/src/main.ts
          include: |
            deno.json
            smith.pizza/deno.json
            smith.pizza/src
          exclude: |
            **/*.test.ts

  deploy-jagoff-me-dev:
    name: Deploy jagoff.me dev
    if: github.event_name == 'workflow_dispatch'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          make jagoff.me/deploy

  deploy-jagoff-me-prod:
    name: Deploy jagoff.me prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          export DEPLOY_ENV="prod"
          make jagoff.me/deploy
