name: Workflow
on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - run: |
          pnpm i --frozen-lockfile
          make check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - run: |
          pnpm i --frozen-lockfile
          make test

  deploy-dev:
    name: Deploy michaelsmith.xyz dev
    if: github.event_name == 'workflow_dispatch'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          make michaelsmith.xyz/deploy

  deploy-prod:
    name: Deploy michaelsmith.xyz prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          export DEPLOY_ENV="prod"
          make michaelsmith.xyz/deploy

  deploy-smith-pizza-dev:
    name: Deploy smith.pizza dev
    if: github.event_name == 'workflow_dispatch'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          make smith.pizza/deploy

  deploy-smith-pizza-prod:
    name: Deploy smith.pizza prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          export DEPLOY_ENV="prod"
          make smith.pizza/deploy

  deploy-jagoff-me-dev:
    name: Deploy jagoff.me dev
    if: github.event_name == 'workflow_dispatch'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          make jagoff.me/deploy

  deploy-jagoff-me-prod:
    name: Deploy jagoff.me prod
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup-pnpm
      - env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm i --frozen-lockfile
          export DEPLOY_ENV="prod"
          make jagoff.me/deploy
